sudo: false

language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
os:
  - linux

env: ELM_VERSION=0.19.0

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@0.19.0-beta8 elm-format@0.8.0 elm-verify-examples@3.0.0

script:
  - elm-format --validate src tests
  - elm make
  - elm-test
  # Use the elm-test path of the global one, instead the one installed with
  # `elm-verify-examples`
  - elm-verify-examples --elm-test=$(npm config get prefix)/elm-verify-examples/node_modules/.bin/elm-test
