sudo: false

language: elm
elm:
  - elm@0.19.1
elm-test: 0.19.1-revision4
elm-format: 0.8.3
node_js:
  - 8

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
os:
  - linux

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - node --version
  - npm --version
  - npm install -g elm-verify-examples@5.0.0

script:
  - elm-format --validate src tests
  - elm make
  - ./execute-tests
